// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Section struct {
	ID        string `json:"id"`
	PageStart int    `json:"PageStart"`
	PageEnd   int    `json:"PageEnd"`
	Subject   string `json:"Subject"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
